[package]
name = "kopek"
version = "0.1.0"
authors = ["zehreken <zehreken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.10.0"
audrey = "0.2.0"
nannou = "0.14.1"
num = "0.3.0"
pprof = { version = "0.3", features = ["flamegraph"] } 

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false