[package]
name = "kopek"
version = "0.1.0"
authors = ["zehreken <zehreken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audrey = "0.2.0"
num = "0.3.1"
pprof = { version = "0.3", features = ["flamegraph"] } 

[dev-dependencies]
criterion = "0.3"
bevy = "0.3.0"
cpal = "0.10.0"
audrey = "0.2.0"
ringbuf = "0.2.2"
nannou = "0.15.0"
nannou_audio = "0.15.0"

[[bench]]
name = "benchmark"
harness = false